name: Build and Deploy AgenticAI

on:
  push:
    branches:
      - main  # change if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 1: Clear Azure Python environment (no caching issues)
    - name: Clear Python packages on Azure
      uses: azure/cli@v2
      with:
        inlineScript: |
          az webapp ssh --name AgenticAI --resource-group <RG_NAME> --command "rm -rf /home/site/wwwroot/.python_packages /antenv"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

    # Step 2: Deploy to Azure App Service
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: AgenticAI
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .
        enable-oryx-build: true

    # Step 3: Post-deploy check for correct Azure Identity version
    - name: Verify Azure Identity installation
      uses: azure/cli@v2
      with:
        inlineScript: |
          az webapp ssh --name AgenticAI --resource-group <RG_NAME> --command "python3 -c 'import azure.identity; import azure.identity._credentials.app_service as a; import pkg_resources; print(\"Azure Identity version:\", pkg_resources.get_distribution(\"azure-identity\").version); print(\"App Service Credential module found:\", a)'"
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
