name: Build and Deploy AgenticAI to Azure WebApp

on:
  push:
    branches:
      - main  # Deploy only on pushes to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Create a deployment package without unnecessary files
      - name: Create deployment package
        run: |
          mkdir package
          cp -r app.py requirements.txt package/
          # Copy any other needed folders (templates, static, etc.)
          if [ -d "templates" ]; then cp -r templates package/; fi
          if [ -d "static" ]; then cp -r static package/; fi
          cd package
          zip -r ../deployment.zip .

      # Upload the zip as an artifact (optional, useful for debugging)
      - name: Upload deployment artifact
        uses: actions/upload-artifact@v4
        with:
          name: deployment-package
          path: deployment.zip

      - name: Deploy to Azure WebApp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'agenticai' # Your Azure WebApp name
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: deployment.zip
