name: Deploy Flask App to Azure App Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (from Azure public feed)
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --extra-index-url https://pkgs.dev.azure.com/azure-public/pypi/_packaging/azure-ai-python/simple/

      - name: Zip app for deployment
        run: zip -r app.zip .

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: agentic-agenthost  # Replace this
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: app.zip
