name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create startup.sh from startup.txt
        run: |
          echo "gunicorn app:app" > startup.sh
          chmod +x startup.sh

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: agentic-agenthost
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
          startup-command: ./startup.sh
