name: build-and-deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies (force reinstall)
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir --force-reinstall -r requirements.txt

      - name: Deploy to Azure Web App (publish profile)
        uses: azure/webapps-deploy@v2
        with:
          app-name: AgenticAI                       # <-- keep your actual app name
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: .
